_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
            "3":
                - 2
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 1
                - 3
                - 5
            "10":
                - 20
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 16
epochs:
    value: 5
iteration:
    value: 1
learning_rate:
    value: 2e-05
max_length:
    value: 512
model:
    value: distilbert-base-uncased
sample_size_per_class:
    value: 100
